name: biomedical_image_segmentation
channels:
  - conda-forge
dependencies:
  - black
  - flake8
  - ipykernel
  - jupyterlab
  - matplotlib
  - numpy
  - opencv
  - pillow
  - pip
  - pytest
  - python=3.9.2
  - scipy
  - pip:
    - torch==1.8.1
    - torchvision==0.9.1
